# Generated by `buidl init`. Edit freely — buidl never regenerates this file.
# syntax=docker/dockerfile:1

# None of these stages is pinned to $BUILDPLATFORM, and that is intentional.
# The installed node_modules ends up in the runtime image, and npm resolves
# prebuilt binaries by the architecture it is running on: node-gyp addons
# (bcrypt, better-sqlite3, sharp) and platform-specific optional dependencies
# (@rollup/rollup-linux-*, @esbuild/linux-*) would all be fetched or compiled
# for the builder. The image would then crash at startup with "invalid ELF
# header". Building on the target platform — under emulation when they differ —
# is the price of a node_modules tree that matches the runtime.
FROM node:22-alpine AS deps
WORKDIR /app

# Lockfile-only copy keeps the install layer cached across source changes.
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app .

# The build stage's node_modules includes dev dependencies. Replace it with a
# production-only tree; this must happen after the COPY, or the copy would
# overwrite it.
COPY package.json package-lock.json ./
RUN rm -rf node_modules && npm ci --omit=dev && npm cache clean --force

EXPOSE 3000
ENV PORT=3000
# The node image ships an unprivileged "node" user at uid 1000. Declared
# numerically because Kubernetes cannot verify a named user against runAsNonRoot.
USER 1000:1000
CMD ["npm", "run", "start"]
