import { spawnSync } from "node:child_process";
import { DEFAULT_MAX_ATTEMPTS } from "@/features/pricing/math";

export type KnownHarness = {
  slug: string;
  bin: string;
  argv: string[];
};

export const KNOWN_HARNESSES: KnownHarness[] = [
  {
    slug: "chatgpt",
    bin: "codex",
    argv: [
      "codex",
      "exec",
      "--json",
      "--skip-git-repo-check",
      "--model",
      "{model}",
      "-c",
      "model_reasoning_effort={effort}",
      "{prompt}",
    ],
  },
  {
    slug: "claude",
    bin: "claude",
    argv: [
      "claude",
      "--print",
      "--model",
      "{model}",
      "--effort",
      "{effort}",
      "--output-format",
      "json",
      "{prompt}",
    ],
  },
  {
    slug: "deepseek",
    bin: "deepcode",
    argv: [
      "deepcode",
      "--print",
      "--model",
      "{model}",
      "--output-format",
      "json",
      "{prompt}",
    ],
  },
  {
    slug: "gemini",
    bin: "gemini",
    argv: [
      "gemini",
      "--prompt",
      "{prompt}",
      "--model",
      "{model}",
      "--output-format",
      "json",
    ],
  },
  {
    slug: "grok",
    bin: "grok",
    argv: [
      "grok",
      "--single",
      "{prompt}",
      "--model",
      "{model}",
      "--reasoning-effort",
      "{effort}",
      "--output-format",
      "json",
    ],
  },
  {
    slug: "kimi",
    bin: "kimi",
    argv: [
      "kimi",
      "--prompt",
      "{prompt}",
      "--model",
      "{model}",
      "--output-format",
      "stream-json",
    ],
  },
  {
    slug: "opencode",
    bin: "opencode",
    argv: [
      "opencode",
      "run",
      "--model",
      "{model}",
      "--variant",
      "{effort}",
      "--format",
      "json",
      "{prompt}",
    ],
  },
  {
    slug: "pi",
    bin: "pi",
    argv: ["pi", "--mode", "json", "--model", "{model}", "{prompt}"],
  },
  {
    slug: "qwen",
    bin: "qwen",
    argv: [
      "qwen",
      "--prompt",
      "{prompt}",
      "--model",
      "{model}",
      "--output-format",
      "json",
    ],
  },
];

export function binOnPath(bin: string, pathEnv = process.env.PATH ?? ""): boolean {
  if (!bin || bin.includes("/") || bin.includes("\\")) return false;
  const probe = spawnSync(process.platform === "win32" ? "where" : "which", [bin], {
    env: { ...process.env, PATH: pathEnv },
    encoding: "utf8",
  });
  return probe.status === 0;
}

export function detectHarnesses(pathEnv?: string): {
  present: KnownHarness[];
  missing: KnownHarness[];
} {
  const present: KnownHarness[] = [];
  const missing: KnownHarness[] = [];
  for (const harness of KNOWN_HARNESSES) {
    if (binOnPath(harness.bin, pathEnv ?? process.env.PATH ?? "")) present.push(harness);
    else missing.push(harness);
  }
  return { present, missing };
}

export function renderEvalYaml(opts: {
  present: KnownHarness[];
  missing: KnownHarness[];
  maxAttempts?: number;
  includeMissing?: boolean;
}): string {
  const maxAttempts = opts.maxAttempts ?? DEFAULT_MAX_ATTEMPTS;
  const lines = [
    "# Generated by metered-eval init. Edit argv to match your real flags.",
    "# Placeholders: {prompt} {prompt_file} {model} {task_id} {setting} {effort}",
    "# Effort is none | low | medium | high | xhigh | max | default.",
    "#",
    "# $ / MU is only defined when every official task passed.",
    "",
    `max_attempts: ${maxAttempts}`,
    "default_effort: default",
    "",
    "harnesses:",
    "  api:",
    "    type: api",
    "    base_url: https://openrouter.ai/api/v1",
  ];

  for (const harness of opts.present) {
    lines.push("");
    lines.push(`  ${harness.slug}:`);
    lines.push("    type: command");
    lines.push(`    argv: [${harness.argv.map(yamlQuote).join(", ")}]`);
  }

  if (opts.includeMissing && opts.missing.length > 0) {
    lines.push("");
    lines.push("  # Not on PATH. Uncomment if you install them.");
    for (const harness of opts.missing) {
      lines.push(`  # ${harness.slug}:`);
      lines.push("  #   type: command");
      lines.push(`  #   argv: [${harness.argv.map(yamlQuote).join(", ")}]`);
    }
  } else if (opts.missing.length > 0) {
    lines.push("");
    lines.push(`  # Looked for, not on PATH: ${opts.missing.map((item) => item.bin).join(", ")}`);
  }

  lines.push("");
  return lines.join("\n");
}

function yamlQuote(value: string): string {
  if (/^[{][a-z_]+[}]$/.test(value) || /^[A-Za-z0-9_./:-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}
